name: Npm deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy:

    runs-on: ubuntu-latest

    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        # TAG: ${{ github.ref }}
      run: bash ./tools/publish.sh
    
    - name: Test action
      uses: blocklet/action-release-to-github@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
